=== martinapm/0373-LMSG/UNIDAD 01/EJERCICIOS XML, XSL Y DTD/students.dtd
<!ELEMENT students (student+)> 
<!ELEMENT student (name, age, major)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT age (#PCDATA)> 
<!ELEMENT major (#PCDATA)>

=== martinapm/0373-LMSG/UNIDAD 01/EJERCICIOS XML, XSL Y DTD/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
<student>
<name>Ana Gómez</name>
<age>20</age>
<major>Informática</major>
</student>
<student>
<name>Carlos Rodríguez</name>
<age>22</age>
<major>Matemáticas</major>
</student>
</students>
